blog/urls.py
from django.urls import path

from blog.views import BlogList

app_name = 'blog'

urlpatterns = [
   path('', BlogList.as_view(), name='blog-list'),
]

eliheist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('projects/', include('projects.urls', namespace='projects')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import HomeView

app_name = 'main'

urlpatterns = [
   path('', HomeView.as_view(), name='home'),
]

projects/urls.py
from django.urls import path

from projects.views import ProjectList

app_name = 'projects'

urlpatterns = [
   path('', ProjectList.as_view(), name='project-list'),
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField()
    body = models.TextField(max_length=2000)
    source_code = models.CharField(max_length=1080, null=True, blank=True)
    tags = models.ManyToManyField('Tag', related_name='tags', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

main/models.py
from django.db import models

projects/models.py
from django.conf.urls import url
from django.db import models

# Create your models here.
class Project(models.Model):
   name = models.CharField(max_length=20)
   thumbnail = models.ImageField()
   link = models.CharField(max_length=1080)

   def __str__(self):
        return self.name

api/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView

from blog.models import Post

# Create your views here.
class BlogList(ListView):
   model = Post
   context_object_name='posts'
   template_name = 'blog/blog-list.html'

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
   template_name = 'main/index.html'

projects/views.py
from django.shortcuts import render
from django.urls.conf import include
from django.views.generic import ListView

from projects.models import Project

# Create your views here.
class ProjectList(ListView):
   model = Project
   context_object_name = 'projects'
   template_name = 'projects/project-list.html'
   

blog/templates/blog/blog-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
   <div class="row">
      {% for post in posts %}
      <div class="col col-lg-6">
         <div class="row post ">
            <div class="col col-sm-6">
               <div class="card-img img-control">
                  <img src="{{ post.thumbnail.url }}" alt="">
               </div>
            </div>
            <div class="col col-sm-6">
               <div class="card-body">
                  <h2 class="card-title">{{ post.title }}</h2>

                  <p class="muted">{{ post.created }}</p>
               </div>
            </div>
         </div>
      </div>
      {% endfor %}
   </div>
</div>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
Home
{% endblock content %}

projects/templates/projects/project-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% for project in projects %}
<div class="project">
   <h3>{{ project.name }}</h3>
</div>
{% endfor %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="{% static 'css/main.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="icon" href="{% static 'assets/favicon.png' %}">
   {% block styles %}
   
   {% endblock styles %}
   <title>eli Heist</title>
</head>
<body>
   <main class="bg-secondary">
      {% include 'header.html' %}
      {% block content %}
      
      {% endblock content %}
      {% include 'footer.html' %}
   </main>
   {% block scripts %}
   {% endblock scripts %}
</body>
</html>

templates/header.html
<header class="">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
            <a class="navbar-brand" href="#">
               <span class="text-primary">Eli</span>Heist
            </a>
            <button
               class="navbar-toggler"
               type="button"
               data-bs-toggle="collapse"
               data-bs-target="#mainNav"
            >
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainNav">
               <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'blog:blog-list' %}">Blog</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'projects:project-list' %}">Projects</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link fw-bold text-primary" href="contact.html">Contact</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
</header>